### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by jpabanil** [thanks-to-it/wp-fontawesome-iconpicker-control#1]
Hello,

Please add documentation on how can I use this on my current plugin plz.. Thanks :)

**Comment by pablo-sg-pacheco** [comment]
Hello @jpabanil ,
I've never thought someone would find it useful :)

I just created a readme for you.
Please give it a try and let me know.

But to be honest I'm not sure if it will work 100%

**Comment by pablo-sg-pacheco** [comment]
Anyway, please take a look at this project:
https://kirki.org/
